import 'package:flutter/material.dart';
import 'package:foodmarket/shared/shared.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
import 'package:supercharged/supercharged.dart';
// import 'package:get/get.dart';
import 'package:foodmarket/models/models.dart';
part 'custom_nav.dart';
part 'rating_start.dart';
part 'food_card.dart';
part 'custom_tabar.dart';
part 'food_list_items.dart';
part 'order_list_items.dart';
